---
- name: Deploy BookMyShow Application
  hosts: kubernetes_master
  become: true
  tasks:
    - name: Clone the latest repository to the Master Node
      git:
        repo: 'https://github.com/15Vaibhavparte/BookMyShow.git'
        dest: /tmp/BookMyShow
        version: main
        force: yes

    - name: Apply all Kubernetes manifests in the kubernetes folder
      command: kubectl apply -f /tmp/BookMyShow/kubernetes/

    - name: Force Kubernetes to pull the new Docker image
      command: kubectl rollout restart deployment bookmyshow-app