apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookmyshow-app
  labels:
    app: bms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bms
  template:
    metadata:
      labels:
        app: bms
    spec:
      containers:
      - name: bookmyshow-app-container
        image: parte15/bookmyshow-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000 